In [56]:
import pandas as pd
import numpy as np

# Load the CSV file
df = pd.read_csv('ODI Cricket Data new.csv')

# First look at the data
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1540 entries, 0 to 1539
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   player_name               1540 non-null   object
 1   role                      1540 non-null   object
 2   total_runs                1540 non-null   int64 
 3   strike_rate               1540 non-null   object
 4   total_balls_faced         1540 non-null   int64 
 5   total_wickets_taken       1540 non-null   int64 
 6   total_runs_conceded       1540 non-null   int64 
 7   total_overs_bowled        1540 non-null   int64 
 8   total_matches_played      1540 non-null   int64 
 9   matches_played_as_batter  1540 non-null   int64 
 10  matches_played_as_bowler  1540 non-null   int64 
 11  matches_won               1540 non-null   int64 
 12  matches_lost              1540 non-null   int64 
 13  player_of_match_awards    1540 non-null   int64 
 14  team                    

player_name    role  total_runs            strike_rate  \
0         V Kohli  Batter       13784  9.170.381.212.161.530   
1   KC Sangakkara  Batter       11618  7.939.046.057.127.230   
2       RG Sharma  Batter       10646  9.035.817.348.497.700   
3        MS Dhoni  Batter       10274  8.497.932.175.351.530   
4  AB de Villiers  Batter        9435  9.944.139.966.273.180   

   total_balls_faced  total_wickets_taken  total_runs_conceded  \
0              15031                    7                  681   
1              14634                    0                    0   
2              11782                   11                  538   
3              12090                    1                   32   
4               9488                    7                  205   

   total_overs_bowled  total_matches_played  matches_played_as_batter  \
0                 671                   579                       579   
1                   0                   510                       510   
2                 614                   577                       577   
3                  38                   575                       575   
4                 201                   466                       466   

   matches_played_as_bowler  matches_won  matches_lost  \
0                         0          360           219   
1                         0          237           273   
2                         0          358           219   
3                         0          356           219   
4                         0          286           180   

   player_of_match_awards          team                average percentage  
0                      41         India  1.969.142.857.142.850    477,93%  
1                      26     Sri Lanka                      0    442,17%  
2                      23         India  9.678.181.818.181.810    474,25%  
3                      20         India                10274.0    458,87%  
4                      26  South Africa  1.347.857.142.857.140    497,97%

PART1 - Numpy Operations

In [8]:
#Fixed Type Arrays

name_array = np.array(df['player_name'], dtype='<U30')  # Up to 30-character strings

print("Fixed-type array (Player Names):")
print(name_array[:5])

Fixed-type array (Player Names):
['V Kohli' 'KC Sangakkara' 'RG Sharma' 'MS Dhoni' 'AB de Villiers']


In [9]:
# Creating a NumPy array from the 'total_runs' column

runs_array = np.array(df['total_runs'], dtype=np.int32)

print("Runs Array:")
print(runs_array[:5])
print("Data type:", runs_array.dtype)

# Array Indexing

print("First player’s runs:", runs_array[0])
print("Third player’s runs:", runs_array[2])
print("Last player’s runs:", runs_array[-1])

Runs Array:
[13784 11618 10646 10274  9435]
Data type: int32
First player’s runs: 13784
Third player’s runs: 10646
Last player’s runs: 0


In [11]:
# Array Slicing
print("First 5 players’ runs:", runs_array[:5])
print("Players runs of 5 to 10:", runs_array[5:10])
print("Every second player’s runs (first 10):", runs_array[:10:2])


First 5 players’ runs: [13784 11618 10646 10274  9435]
Players runs of 5 to 10: [9212 8126 8040 7834 7648]
Every second player’s runs (first 10): [13784 10646  9435  8126  7834]


In [12]:
# Reshaping Arrays

reshaped_runs = runs_array[:10].reshape(5, 2)  # Take first 10 runs and reshape to 5 rows, 2 columns

print("Reshaped array (5 rows x 2 cols):")
print(reshaped_runs)


Reshaped array (5 rows x 2 cols):
[[13784 11618]
 [10646 10274]
 [ 9435  9212]
 [ 8126  8040]
 [ 7834  7648]]


In [15]:
# Concatenation
first_part = runs_array[:5]
second_part = runs_array[5:10]
print(first_part)
print(second_part)

combined = np.concatenate([first_part, second_part])
print("Concatenated Array:")
print(combined)

[13784 11618 10646 10274  9435]
[9212 8126 8040 7834 7648]
Concatenated Array:
[13784 11618 10646 10274  9435  9212  8126  8040  7834  7648]


In [16]:
split_arrays = np.split(combined, 2)
print("Split Arrays:")
print(split_arrays[0])  # First half
print(split_arrays[1])  # Second half

Split Arrays:
[13784 11618 10646 10274  9435]
[9212 8126 8040 7834 7648]


In [33]:
# # Select first 5 run values
runs_array = np.array(df['total_runs'], dtype=np.float32)
sample_runs = runs_array[:20]

# Universal Functions
sqrt_runs = np.sqrt(sample_runs)
log_runs = np.log1p(sample_runs)        # log(1 + x)
squared_runs = np.power(sample_runs, 2)
exp_runs = np.exp(sample_runs / 1000)   # Exponential growth (scaled down to avoid overflow)
sin_runs = np.sin(sample_runs)          # Sine for fun
clipped_runs = np.clip(sample_runs, 0, 1000)  # Limit values between 0 and 1000

print("Original Runs:", sample_runs)
print("Square Roots:", sqrt_runs)
print("Log(1 + x):", log_runs)
print("Squared:", squared_runs)
print("Exponential:", exp_runs)
print("Sine:", sin_runs)
print("Clipped to max 1000:", clipped_runs)


Original Runs: [13784. 11618. 10646. 10274.  9435.  9212.  8126.  8040.  7834.  7648.
  7125.  7094.  6988.  6979.  6953.  6868.  6733.  6661.  6623.  6482.]
Square Roots: [117.40528  107.78683  103.17946  101.36074   97.13393   95.979164
  90.144325  89.666046  88.50989   87.45284   84.40971   84.22588
  83.59426   83.54041   83.38465   82.8734    82.05486   81.61495
  81.38181   80.51087 ]
Log(1 + x): [9.531337  9.360397  9.273033  9.237469  9.1522875 9.128371  9.002947
 8.992309  8.966356  8.94233   8.871506  8.867146  8.852093  8.850804
 8.847073  8.834774  8.814924  8.804175  8.798454  8.776938 ]
Squared: [1.8999866e+08 1.3497792e+08 1.1333731e+08 1.0555508e+08 8.9019224e+07
 8.4860944e+07 6.6031876e+07 6.4641600e+07 6.1371556e+07 5.8491904e+07
 5.0765624e+07 5.0324836e+07 4.8832144e+07 4.8706440e+07 4.8344208e+07
 4.7169424e+07 4.5333288e+07 4.4368920e+07 4.3864128e+07 4.2016324e+07]
Exponential: [9.6898112e+05 1.1107934e+05 4.2024156e+04 2.8969539e+04 1.2518971e+04
 1.0016609e+0

In [19]:
# Aggregations on 'total_wickets_taken'

wickets_array = np.array(df['total_wickets_taken'], dtype=np.int32)

print("Total Wickets:", np.sum(wickets_array))
print("Average Wickets:", np.mean(wickets_array))
print("Maximum Wickets:", np.max(wickets_array))
print("Minimum Wickets:", np.min(wickets_array))
print("Standard Deviation:", np.std(wickets_array))


Total Wickets: 16812
Average Wickets: 10.916883116883117
Maximum Wickets: 343
Minimum Wickets: 0
Standard Deviation: 27.91847315903563


In [53]:
# Broadcasting example: Add 5 bonus wickets to each player

bonus_wickets = wickets_array + 5

print("Original Wickets:", wickets_array[:10])
print("With Bonus Wickets:", bonus_wickets[:5])


Original Wickets: [ 7  0 11  1  7 97  0  2  0  0]
With Bonus Wickets: [12  5 16  6 12]


In [34]:
# Comparisons: Players with more than 5000 runs on total_runs

runs = np.array(df['total_runs'], dtype=np.int32)
high_scorers_mask = runs > 5000  #comparing and adding boolean values

print("Boolean Mask (first 10):", high_scorers_mask[:20])
print("Number of high scorers:", np.sum(high_scorers_mask))  # Counts Trues


Boolean Mask (first 10): [ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True]
Number of high scorers: 37


In [36]:
# Boolean Indexing: Get names of players with >5000 runs

names = np.array(df['player_name'])
high_scorers = names[runs > 5000]   #adding the names of players more than 5000

print("Players with more than 5000 runs:")
print(high_scorers)


Players with more than 5000 runs:
['V Kohli' 'KC Sangakkara' 'RG Sharma' 'MS Dhoni' 'AB de Villiers'
 'TM Dilshan' 'LRPL Taylor' 'DPMD Jayawardene' 'HM Amla' 'Tamim Iqbal'
 'MJ Guptill' 'Mushfiqur Rahim' 'MJ Clarke' 'RT Ponting' 'EJG Morgan'
 'Yuvraj Singh' 'S Dhawan' 'Q de Kock' 'DA Warner' 'WU Tharanga'
 'CH Gayle' 'SR Tendulkar' 'Mohammad Hafeez' 'V Sehwag' 'Babar Azam'
 'AD Mathews' 'SK Raina' 'SPD Smith' 'F du Plessis' 'SR Watson' 'IR Bell'
 'AJ Finch' 'BB McCullum' 'BRM Taylor' 'Mahmudullah' 'MEK Hussey'
 'JC Buttler']


In [42]:
# Fancy Indexing: Select specific players by index

selected_indices = [0, 3, 7, 10, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 355, 37, 39, 41]
selected_names = names[selected_indices]
selected_runs = runs[selected_indices]

print("Selected Players:", selected_names)
print("Their Runs:", selected_runs)


Selected Players: ['V Kohli' 'MS Dhoni' 'DPMD Jayawardene' 'MJ Guptill' 'RT Ponting'
 'Yuvraj Singh' 'Q de Kock' 'WU Tharanga' 'SR Tendulkar' 'V Sehwag'
 'AD Mathews' 'SPD Smith' 'SR Watson' 'AJ Finch' 'BRM Taylor'
 'CJ Ferguson' 'SD Hope' 'JP Duminy' 'Misbah-ul-Haq']
Their Runs: [13784 10274  8040  7125  6979  6868  6661  6482  6432  5692  5646  5549
  5357  5188  5130   663  4989  4928  4752]


In [49]:
# Fast Sorting

# Convert columns to NumPy arrays
names = np.array(df['player_name'])
runs = np.array(df['total_runs'], dtype=np.int32)

# Sort runs and get top 100 indices (highest to lowest)
sorted_indices = np.argsort(runs)[-100:][::-1]

# Print top 100 names with their runs
print("Top 100 Players by Total Runs:\n")
for i in sorted_indices:
    print(f"{names[i]}: {runs[i]} runs")



Top 100 Players by Total Runs:

V Kohli: 13784 runs
KC Sangakkara: 11618 runs
RG Sharma: 10646 runs
MS Dhoni: 10274 runs
AB de Villiers: 9435 runs
TM Dilshan: 9212 runs
LRPL Taylor: 8126 runs
DPMD Jayawardene: 8040 runs
HM Amla: 7834 runs
Tamim Iqbal: 7648 runs
MJ Guptill: 7125 runs
Mushfiqur Rahim: 7094 runs
MJ Clarke: 6988 runs
RT Ponting: 6979 runs
EJG Morgan: 6953 runs
Yuvraj Singh: 6868 runs
S Dhawan: 6733 runs
Q de Kock: 6661 runs
DA Warner: 6623 runs
WU Tharanga: 6482 runs
CH Gayle: 6433 runs
SR Tendulkar: 6432 runs
Mohammad Hafeez: 6351 runs
V Sehwag: 5692 runs
Babar Azam: 5659 runs
AD Mathews: 5646 runs
SK Raina: 5585 runs
SPD Smith: 5549 runs
F du Plessis: 5445 runs
SR Watson: 5357 runs
IR Bell: 5289 runs
AJ Finch: 5188 runs
BB McCullum: 5157 runs
BRM Taylor: 5130 runs
Mahmudullah: 5127 runs
MEK Hussey: 5076 runs
JC Buttler: 5018 runs
SD Hope: 4989 runs
G Gambhir: 4981 runs
JP Duminy: 4928 runs
Younis Khan: 4777 runs
Misbah-ul-Haq: 4752 runs
DA Miller: 4466 runs
ST Jayasuriya

In [27]:
#partial Sorting
# Get indices of top 5 run scorers
top_indices = np.argsort(runs)[-5:]

# Reverse for highest first
top_indices = top_indices[::-1]

# Print names and runs
print("Top 5 Run Scorers:")
for idx in top_indices:
    print(names[idx], ":", runs[idx])

Top 5 Run Scorers:
V Kohli : 13784
KC Sangakkara : 11618
RG Sharma : 10646
MS Dhoni : 10274
AB de Villiers : 9435


In [50]:
# Structured Array using actual dataset columns

player_names = np.array(df['player_name'])
runs = np.array(df['total_runs'], dtype=np.int32)
wickets = np.array(df['total_wickets_taken'], dtype=np.int32)

# Create structured array (first 5 players)
structured_data = np.array([
    (player_names[i], runs[i], wickets[i]) for i in range(20)
], dtype=[('name', 'U30'), ('runs', 'i4'), ('wickets', 'i4')])

print("Structured Array:")
print(structured_data)

# Access fields(Normal Method)
print("\nPlayer Names:", structured_data['name'])
print("Runs:", structured_data['runs'])
print("Wickets:", structured_data['wickets'])


Structured Array:
[('V Kohli', 13784,  7) ('KC Sangakkara', 11618,  0)
 ('RG Sharma', 10646, 11) ('MS Dhoni', 10274,  1)
 ('AB de Villiers',  9435,  7) ('TM Dilshan',  9212, 97)
 ('LRPL Taylor',  8126,  0) ('DPMD Jayawardene',  8040,  2)
 ('HM Amla',  7834,  0) ('Tamim Iqbal',  7648,  0)
 ('MJ Guptill',  7125,  4) ('Mushfiqur Rahim',  7094,  0)
 ('MJ Clarke',  6988, 56) ('RT Ponting',  6979,  0)
 ('EJG Morgan',  6953,  0) ('Yuvraj Singh',  6868, 99)
 ('S Dhawan',  6733,  0) ('Q de Kock',  6661,  0) ('DA Warner',  6623,  0)
 ('WU Tharanga',  6482,  0)]

Player Names: ['V Kohli' 'KC Sangakkara' 'RG Sharma' 'MS Dhoni' 'AB de Villiers'
 'TM Dilshan' 'LRPL Taylor' 'DPMD Jayawardene' 'HM Amla' 'Tamim Iqbal'
 'MJ Guptill' 'Mushfiqur Rahim' 'MJ Clarke' 'RT Ponting' 'EJG Morgan'
 'Yuvraj Singh' 'S Dhawan' 'Q de Kock' 'DA Warner' 'WU Tharanga']
Runs: [13784 11618 10646 10274  9435  9212  8126  8040  7834  7648  7125  7094
  6988  6979  6953  6868  6733  6661  6623  6482]
Wickets: [ 7  0 11  1  7

In [52]:
# Convert to Record Array
record_data = structured_data.view(np.recarray)

# Example: Print name + runs in a loop
print("\nPlayer Performances:")
for i in range(20):
    print(f"{record_data.name[i]} - {record_data.runs[i]} runs, {record_data.wickets[i]} wickets")


Player Performances:
V Kohli - 13784 runs, 7 wickets
KC Sangakkara - 11618 runs, 0 wickets
RG Sharma - 10646 runs, 11 wickets
MS Dhoni - 10274 runs, 1 wickets
AB de Villiers - 9435 runs, 7 wickets
TM Dilshan - 9212 runs, 97 wickets
LRPL Taylor - 8126 runs, 0 wickets
DPMD Jayawardene - 8040 runs, 2 wickets
HM Amla - 7834 runs, 0 wickets
Tamim Iqbal - 7648 runs, 0 wickets
MJ Guptill - 7125 runs, 4 wickets
Mushfiqur Rahim - 7094 runs, 0 wickets
MJ Clarke - 6988 runs, 56 wickets
RT Ponting - 6979 runs, 0 wickets
EJG Morgan - 6953 runs, 0 wickets
Yuvraj Singh - 6868 runs, 99 wickets
S Dhawan - 6733 runs, 0 wickets
Q de Kock - 6661 runs, 0 wickets
DA Warner - 6623 runs, 0 wickets
WU Tharanga - 6482 runs, 0 wickets


PART2- Pandas and its Operations 

In [57]:
#Series object

# Select multiple columns to display
columns_to_show = ['player_name', 'role', 'total_runs', 'strike_rate', 'total_wickets_taken']

# Create a new DataFrame with selected columns
runs_df = df[columns_to_show].reset_index()
runs_df.columns = ['Index', 'Player Name', 'Role', 'Total Runs', 'Strike Rate', 'Total Wickets']

# Show all rows
pd.set_option('display.max_rows', None)

# Display full table
print(runs_df)

      Index            Player Name    Role  Total Runs  \
0         0                V Kohli  Batter       13784   
1         1          KC Sangakkara  Batter       11618   
2         2              RG Sharma  Batter       10646   
3         3               MS Dhoni  Batter       10274   
4         4         AB de Villiers  Batter        9435   
5         5             TM Dilshan  Batter        9212   
6         6            LRPL Taylor  Batter        8126   
7         7       DPMD Jayawardene  Batter        8040   
8         8                HM Amla  Batter        7834   
9         9            Tamim Iqbal  Batter        7648   
10       10             MJ Guptill  Batter        7125   
11       11        Mushfiqur Rahim  Batter        7094   
12       12              MJ Clarke  Batter        6988   
13       13             RT Ponting  Batter        6979   
14       14             EJG Morgan  Batter        6953   
15       15           Yuvraj Singh  Batter        6868   
16       16   

In [58]:
# General structure of the DataFrame
print("DataFrame Info:")
print(df.info())


DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1540 entries, 0 to 1539
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   player_name               1540 non-null   object
 1   role                      1540 non-null   object
 2   total_runs                1540 non-null   int64 
 3   strike_rate               1540 non-null   object
 4   total_balls_faced         1540 non-null   int64 
 5   total_wickets_taken       1540 non-null   int64 
 6   total_runs_conceded       1540 non-null   int64 
 7   total_overs_bowled        1540 non-null   int64 
 8   total_matches_played      1540 non-null   int64 
 9   matches_played_as_batter  1540 non-null   int64 
 10  matches_played_as_bowler  1540 non-null   int64 
 11  matches_won               1540 non-null   int64 
 12  matches_lost              1540 non-null   int64 
 13  player_of_match_awards    1540 non-null   int64 
 14  team    

In [60]:
#Indexing

# Select specific columns and display as a DataFrame
selected_columns = df[['player_name', 'total_runs', 'strike_rate', 'total_wickets_taken']]

# Show all rows if you like
pd.set_option('display.max_rows', None)

# Display as table
print(selected_columns)


                player_name  total_runs             strike_rate  \
0                   V Kohli       13784   9.170.381.212.161.530   
1             KC Sangakkara       11618   7.939.046.057.127.230   
2                 RG Sharma       10646   9.035.817.348.497.700   
3                  MS Dhoni       10274   8.497.932.175.351.530   
4            AB de Villiers        9435   9.944.139.966.273.180   
5                TM Dilshan        9212   8.547.833.348.798.360   
6               LRPL Taylor        8126   8.093.625.498.007.960   
7          DPMD Jayawardene        8040   7.857.701.329.163.400   
8                   HM Amla        7834   8.648.708.324.133.360   
9               Tamim Iqbal        7648     766.409.459.865.718   
10               MJ Guptill        7125   8.524.766.690.595.830   
11          Mushfiqur Rahim        7094   7.894.502.559.537.050   
12                MJ Clarke        6988   7.683.342.495.876.850   
13               RT Ponting        6979     806.075.306.075.30

In [83]:
#  Select rows using iloc (integer-location based indexing)

# Select the first 5 rows (index 0 to 4)
first_five_rows = df.iloc[0:5]
print("First 5 Rows:")
print(first_five_rows)

# Select a specific row by index — 10th row (index 9)
row_10 = df.iloc[9]
print("\n10th Row:")
print(row_10)

# Select a range of rows — from index 20 to 25
subset_rows = df.iloc[20:26]
print("\nRows 20 to 25:")
print(subset_rows)


First 5 Rows:
      player_name    role  total_runs            strike_rate  \
0         V Kohli  Batter       13784  9.170.381.212.161.530   
1   KC Sangakkara  Batter       11618  7.939.046.057.127.230   
2       RG Sharma  Batter       10646  9.035.817.348.497.700   
3        MS Dhoni  Batter       10274  8.497.932.175.351.530   
4  AB de Villiers  Batter        9435  9.944.139.966.273.180   

   total_balls_faced  total_wickets_taken  total_runs_conceded  \
0              15031                    7                  681   
1              14634                    0                    0   
2              11782                   11                  538   
3              12090                    1                   32   
4               9488                    7                  205   

   total_overs_bowled  total_matches_played  matches_played_as_batter  \
0                 671                   579                       579   
1                   0                   510               

In [65]:
# 🔹 Select rows using loc (label-based indexing)

# Select the row with index label 2
row_2 = df.loc[2]
print("Row with index label 2:")
print(row_2)

# Select rows with labels from 5 to 9 (inclusive)
rows_5_to_9 = df.loc[5:9]
print("\nRows from index label 5 to 9:")
print(rows_5_to_9)


Row with index label 2:
player_name                             RG Sharma
role                                       Batter
total_runs                                  10646
strike_rate                 9.035.817.348.497.700
total_balls_faced                           11782
total_wickets_taken                            11
total_runs_conceded                           538
total_overs_bowled                            614
total_matches_played                          577
matches_played_as_batter                      577
matches_played_as_bowler                        0
matches_won                                   358
matches_lost                                  219
player_of_match_awards                         23
team                                        India
average                     9.678.181.818.181.810
percentage                                474,25%
Name: 2, dtype: object

Rows from index label 5 to 9:
        player_name    role  total_runs            strike_rate  \
5     

In [69]:
# 🔹 Filter players who scored more than 10,000 runs
high_scorers = df[df['total_runs'] > 5000]
print("Players with more than 10,000 runs:")
print(high_scorers[['player_name', 'total_runs','strike_rate']])


Players with more than 10,000 runs:
         player_name  total_runs             strike_rate
0            V Kohli       13784   9.170.381.212.161.530
1      KC Sangakkara       11618   7.939.046.057.127.230
2          RG Sharma       10646   9.035.817.348.497.700
3           MS Dhoni       10274   8.497.932.175.351.530
4     AB de Villiers        9435   9.944.139.966.273.180
5         TM Dilshan        9212   8.547.833.348.798.360
6        LRPL Taylor        8126   8.093.625.498.007.960
7   DPMD Jayawardene        8040   7.857.701.329.163.400
8            HM Amla        7834   8.648.708.324.133.360
9        Tamim Iqbal        7648     766.409.459.865.718
10        MJ Guptill        7125   8.524.766.690.595.830
11   Mushfiqur Rahim        7094   7.894.502.559.537.050
12         MJ Clarke        6988   7.683.342.495.876.850
13        RT Ponting        6979     806.075.306.075.306
14        EJG Morgan        6953   8.951.976.310.029.610
15      Yuvraj Singh        6868   8.545.477.168.097

In [80]:
#Arithemetic Functions

# Calculate average runs per match
df['runs_per_match'] = df['total_runs'] / df['total_matches_played']

# Display selected columns
print(df[['player_name', 'total_runs', 'total_matches_played', 'runs_per_match']].head(30))


         player_name  total_runs  total_matches_played  runs_per_match
0            V Kohli       13784                   579       23.806563
1      KC Sangakkara       11618                   510       22.780392
2          RG Sharma       10646                   577       18.450607
3           MS Dhoni       10274                   575       17.867826
4     AB de Villiers        9435                   466       20.246781
5         TM Dilshan        9212                   510       18.062745
6        LRPL Taylor        8126                   444       18.301802
7   DPMD Jayawardene        8040                   510       15.764706
8            HM Amla        7834                   470       16.668085
9        Tamim Iqbal        7648                   345       22.168116
10        MJ Guptill        7125                   444       16.047297
11   Mushfiqur Rahim        7094                   345       20.562319
12         MJ Clarke        6988                   545       12.822018
13    

In [81]:
# Series Operations on ODI Cricket Dataset

print("🔢 Total Runs Scored:", df["total_runs"].sum())                     # Total Runs
print("📊 Average Strike Rate:", df["total_runs"].mean())                # Average Strike Rate
print("⬇️ Minimum Runs Conceded:", df["total_runs_conceded"].min())       # Min Runs Conceded
print("⬆️ Maximum Overs Bowled:", df["total_overs_bowled"].max())         # Max Overs Bowled
print("\n🏏 Player Roles Count:\n", df["role"].value_counts())             # Count by Player Role


🔢 Total Runs Scored: 973863
📊 Average Strike Rate: 632.3785714285714
⬇️ Minimum Runs Conceded: 0
⬆️ Maximum Overs Bowled: 10803

🏏 Player Roles Count:
 role
Batter    1540
Name: count, dtype: int64


In [85]:
# Apply universal functions to 'total_runs'

sqrt_runs = np.sqrt(df['total_runs'])
log_runs = np.log1p(df['total_runs'])  # log(1 + x)
squared_runs = np.square(df['total_runs'])

# Display sample with index to show index preservation
result_df = pd.DataFrame({
    'Player': df['player_name'],
    'Total Runs': df['total_runs'],
    'Sqrt Runs': sqrt_runs,
    'Log(1+Runs)': log_runs,
    'Runs Squared': squared_runs
})

# Show first 5 rows
print(result_df.head(30))

              Player  Total Runs   Sqrt Runs  Log(1+Runs)  Runs Squared
0            V Kohli       13784  117.405281     9.531336     189998656
1      KC Sangakkara       11618  107.786827     9.360397     134977924
2          RG Sharma       10646  103.179455     9.273033     113337316
3           MS Dhoni       10274  101.360742     9.237469     105555076
4     AB de Villiers        9435   97.133928     9.152287      89019225
5         TM Dilshan        9212   95.979164     9.128371      84860944
6        LRPL Taylor        8126   90.144329     9.002947      66031876
7   DPMD Jayawardene        8040   89.666047     8.992309      64641600
8            HM Amla        7834   88.509886     8.966356      61371556
9        Tamim Iqbal        7648   87.452844     8.942330      58491904
10        MJ Guptill        7125   84.409715     8.871505      50765625
11   Mushfiqur Rahim        7094   84.225887     8.867146      50324836
12         MJ Clarke        6988   83.594258     8.852093      4

In [89]:
#Index Alignment with 'total_runs'

# Group-wise average total runs by team
team_avg_runs = df.groupby("team")["total_runs"].mean()

# Subtract average team runs from each player's runs
df["run_diff_from_team_avg"] = df["total_runs"] - df["team"].map(team_avg_runs)

# Show result with index-aligned columns
result = df[["player_name", "team", "total_runs", "run_diff_from_team_avg"]]
print(result.head(10))


        player_name          team  total_runs  run_diff_from_team_avg
0           V Kohli         India       13784            12746.411765
1     KC Sangakkara     Sri Lanka       11618            10753.982301
2         RG Sharma         India       10646             9608.411765
3          MS Dhoni         India       10274             9236.411765
4    AB de Villiers  South Africa        9435             8483.260870
5        TM Dilshan     Sri Lanka        9212             8347.982301
6       LRPL Taylor   New Zealand        8126             7366.377778
7  DPMD Jayawardene     Sri Lanka        8040             7175.982301
8           HM Amla  South Africa        7834             6882.260870
9       Tamim Iqbal    Bangladesh        7648             7055.168675
